yolov8_image_segmentation:
  ros__parameters:
    yolov8_image_segmentation:
      class_name: blue_tube
      yolo_model_name: "best.pt"
      confidence_threshold: 0.9
      visualize: True
      timeout_seconds: -1