yolo_image_segmentation_multi_object:
  ros__parameters:
    yolo_image_segmentation_multi_object:
      default_class_name: blue_tube
      yolo_model_name: "YOLO11_segA.pt"
      confidence_threshold: 0.9
      visualize: True
      timeout_seconds: -1


#  class_name: ['beaker', 'blue_bottle', 'blue_tube', 'camera', 'distilled water', 'drink bottle', 'dropper', 'funnels', 'graduated cylinder', 'powerbox', 'small_tube', 'transtube', 'white_tube']

